# Generated by Django 3.0.8 on 2020-10-29 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council', models.CharField(choices=[('Albury', 'Albury'), ('Armidale Regional', 'Armidale Regional'), ('Ballina', 'Ballina'), ('Balranald', 'Balranald'), ('Bathurst Regional', 'Bathurst Regional'), ('Bega Valley', 'Bega Valley'), ('Bellingen', 'Bellingen'), ('Blacktown', 'Blacktown'), ('Bland', 'Bland'), ('Blue Mountains', 'Blue Mountains'), ('Broken Hill', 'Broken Hill'), ('Byron', 'Byron'), ('Cabonne', 'Cabonne'), ('Campbelltown', 'Campbelltown'), ('Canada Bay', 'Canada Bay'), ('Canterbury-Blacktown', 'Canterbury-Blacktown'), ('Carrathool', 'Carrathool'), ('Central Coast', 'Central Coast'), ('Cessnock', 'Cessnock'), ('Cobar', 'Cobar'), ('Coffs Harbour', 'Coffs Harbour'), ('Cumberland', 'Cumberland'), ('Eurobodalla', 'Eurobodalla'), ('Fairfield', 'Fairfield'), ('Gunnedah', 'Gunnedah'), ('Gwydir', 'Gwydir'), ('Inner West', 'Inner West'), ('Kyogle', 'Kyogle'), ('Lachlan', 'Lachlan'), ('Lithgow', 'Lithgow'), ('Liverpool', 'Liverpool'), ('Moore Plains', 'Moore Plains'), ('Mosman', 'Mosman'), ('Murray River', 'Murray River'), ('North Sydney', 'North Sydney'), ('Northern Beaches', 'Northern Beaches'), ('Parramatta', 'Parramatta'), ('Snowy Monaro Regional', 'Snowy Monaro Regional'), ('Strathfield', 'Strathfield'), ('Sydney', 'Sydney'), ('Tamworth Regional', 'Tamworth Regional'), ('Weddin', 'Weddin'), ('Wollondilly', 'Wollondilly'), ('Wollongong', 'Wollongong'), ('Woollahra', 'Woollahra'), ('Yass Valley', 'Yass Valley')], max_length=21)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
