# Generated by Django 3.0.8 on 2020-10-29 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('Request', 'Request'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Request', max_length=11)),
                ('problem', models.CharField(choices=[('Waste', 'Waste'), ('Graffiti', 'Graffiti'), ('Vehicles and Parking', 'Vehicles and Parking'), ('Damaged Footpath', 'Damaged Footpath'), ('Tree Maintenance', 'Tree Maintenance'), ('Other', 'Other')], max_length=20)),
                ('street_num', models.IntegerField()),
                ('street_name', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
